# Generated by Django 2.2.5 on 2019-09-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_timestamp', models.DateTimeField(auto_now=True)),
                ('unique_id', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
