# Generated by Django 2.2.5 on 2019-09-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobs',
            table='jobs',
        ),
    ]
