# Generated by Django 2.2.6 on 2019-10-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobs',
            table=None,
        ),
    ]
