# Generated by Django 2.2.5 on 2019-09-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190923_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='entry_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
