# Generated by Django 2.2.5 on 2019-09-23 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190923_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='entry_timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
