# Generated by Django 2.2.6 on 2019-10-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20191009_0758'),
        ('jobs', '0011_job_employer_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer_profile_id',
        ),
        migrations.AddField(
            model_name='job',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
