# Generated by Django 2.2.6 on 2019-10-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20191011_0727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user_id',
            new_name='user',
        ),
    ]
