# Generated by Django 2.2.6 on 2019-10-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20191008_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='description',
            new_name='cover_latter',
        ),
    ]
