# Generated by Django 2.2.6 on 2019-10-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20191011_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='created_at',
            new_name='applied_timestamp',
        ),
    ]
