# Generated by Django 3.1 on 2019-10-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191002_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='document_file',
        ),
    ]
