# Generated by Django 2.2.6 on 2019-10-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20191009_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='years_of_experience',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
