# Generated by Django 2.2.6 on 2019-10-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20191015_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='', error_messages={'required': 'Role must be provided'}, max_length=12),
        ),
    ]
