# Generated by Django 3.1 on 2019-10-01 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191001_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='first_name',
            field=models.CharField(blank=True, error_messages={'required': 'First name must be provided'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='last_name',
            field=models.CharField(blank=True, error_messages={'required': 'Last name must be provided'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='years_of_experience',
            field=models.FloatField(blank=True, default=0.0, error_messages={'required': 'Years of experience must be provided'}, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
