# Generated by Django 3.1 on 2019-10-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191001_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='image_path',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
