# Generated by Django 2.2.6 on 2019-10-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191002_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='employee',
            field=models.ManyToManyField(to='accounts.EmployeeProfile'),
        ),
        migrations.DeleteModel(
            name='EmployeeSkills',
        ),
    ]
