# Generated by Django 2.2.6 on 2019-10-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191002_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.ManyToManyField(to='accounts.Skill'),
        ),
    ]
