# Generated by Django 2.2.6 on 2019-10-03 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_skill_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='user',
        ),
        migrations.AddField(
            model_name='qualification',
            name='employee_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.EmployeeProfile'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
        migrations.AlterModelTable(
            name='employeeprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='employerprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='qualification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='skill',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
