# Generated by Django 2.2.6 on 2019-10-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20191004_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
